.TH TRAWLD 1 "26 July 2024" "Version 0.2.7" "Trawl Daemon"
.SH NAME
trawld \- Configuration Manager daemon for trawl
.SH SYNOPSIS
.B trawld
.RB [ \-\-cpp <filename> ]
.RB [ \-d | \-\-debug ]
.RB [ \-h | \-\-help ]
.RB [ \-l | \-\-load <filename> ]
.RB [ \-\-nocpp ]
.RB [ \-v | \-\-verbose ]
.RB [ \-V | \-\-version ]
.RB [ <FILENAME> ]
.SH DESCRIPTION
Trawl is a resource management tool aimed as an xrdb alternative that is session independent, i.e works on both X11 and Wayland. trawld is a daemon that functions as a backend for the trawl client utilities.
.SH OPTIONS
.TP
.BR \-\-cpp " <filename>"
Preprocessor to use [/usr/bin/cpp]
.TP
.BR \-d ", " \-\-debug
Enable debug mode
.TP
.BR \-h ", " \-\-help
Print help information
.TP
.BR \-l ", " \-\-load " <filename>"
Load resources from file
.TP
.BR \-\-nocpp
Do not use a preprocessor
.TP
.BR \-v ", " \-\-verbose
Enable verbose mode
.TP
.BR \-V ", " \-\-version
Print version information
.SH SEE ALSO
xrdb(1)
.SH AUTHORS
Soumya Ranjan Patnaik <soumyaranjan1812@gmail.com>, Ken Gilmer <kgilmer@gmail.com>
