.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH gpgv-sq 1  "gpgv-sq 0.5.1" 
.SH NAME
gpgv\-sq \- gpgv\-sq \- Verify OpenPGP signatures as gpgv
.SH SYNOPSIS
\fBgpgv\-sq\fR [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-q\fR|\fB\-\-quiet\fR] [\fB\-\-keyring\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-\-ignore\-time\-conflict\fR] [\fB\-\-status\-fd\fR] [\fB\-\-weak\-digest\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
This is a re\-implementation and drop\-in replacement of gpgv using the Sequoia OpenPGP implementation.
.PP
gpgv\-sq is feature\-complete. Please report any problems you encounter when replacing gpgv with gpgv\-sq.
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
verbose
.TP
\fB\-q\fR, \fB\-\-quiet\fR
be somewhat more quiet
.TP
\fB\-\-keyring\fR=\fIFILE\fR
take the keys from the keyring FILE
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
write output to FILE
.TP
\fB\-\-ignore\-time\-conflict\fR
make timestamp conflicts only a warning
.TP
\fB\-\-status\-fd\fR=\fIFD\fR
write status info to this FD
.TP
\fB\-\-weak\-digest\fR=\fIALGO\fR
reject signatures made with ALGO
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH VERSION
v0.5.1
