#!/bin/bash
for i in src/*/debian/RFS; do
    echo "$(git log -1 --pretty="format:%ct" "$i")" "$i"
done | sort  | while read t i; do
    pkg=$(basename "$(dirname "$(dirname "$i")")")
    if test -n "$(git --no-pager branch --remotes -l origin/pending-"$pkg")"; then
        # If a pending branch exists, skip it
        continue
    fi
    echo -e "$(date -d@"$t") \e[32m$pkg\e[0m"
    if ! head -1 $(dirname "$i")/changelog |grep -q UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO; then
        echo -e "\e[31mRFS but the first line of the changelog doesn't contain UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO\e[0m"
    fi
    if grep -q FIXME $(dirname "$i")/copyright; then
        echo -e "\e[31mRFS but still contains FIXME in debian/copyright\e[0m"
    fi
    if test `grep urgency $(dirname "$i")/changelog|wc -l` -eq 1; then
        # If there is only one item in the changelog, mark the package as NEW
        echo -e "\e[31mNEW package\e[0m"
    fi
    # trim the content
    content=$(xargs '-d\n' echo -n < "$i")
    if test -n "$content"; then
        echo "  $content"
    fi
done
