.TH TRAWLCAT 1 "2022" "trawlcat version" "User Commands"
.SH NAME
trawlcat \- CLI for searching a trawl resource
.SH SYNOPSIS
.B trawlcat
.RI [ NAME ]
.RI [ DEFAULT ]
.SH DESCRIPTION
Trawl is a resource management tool aimed as an xrdb alternative that is session independent, i.e works on both X11 and Wayland. trawlcat is a client CLI utility for searching a trawl resource by key.
.SH OPTIONS
.TP
.BI \-h, \-\-help
Print help information
.TP
.BI \-V, \-\-version
Print version information
.SH ARGUMENTS
.TP
.BI NAME
Resource name
.TP
.BI DEFAULT
Default value for resource
.SH AUTHORS
Soumya Ranjan Patnaik <soumyaranjan1812@gmail.com>, Ken Gilmer <kgilmer@gmail.com>
.SH "SEE ALSO"
trawld(1), trawldb(1)
