.\" Based on the --help output of cargo-rm,
.\" formatted as a man page by Robin Krahl <robin.krahl@ireas.org>
.TH CARGO-RM 1 2020-01-20
.SH NAME
cargo-rm \- remove dependencies from a Cargo.toml manifest file
.SH SYNOPSIS
\fBcargo rm \fIcrate\fR... [\fB\-\-dev\fR|\fB\-\-build\fR] [\fIoptions\fR]
.br
\fBcargo rm \-\-help\fR
.br
\fBcargo rm \-\-version\fR
.SH DESCRIPTION
Remove the dependency \fIcrate\fR from a Cargo.toml manifest file.
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-dev\fR
Remove the crate as development dependency.
.TP
\fB\-B\fR, \fB\-\-build\fR
Remove the crate as build dependency.
.TP
\fB\-\-manifest\-path=\fIpath\fR
Path to the manifest to remove a dependency from.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show version information.
.SH EXAMPLES
Remove a dependency:
    $ \fBcargo rm regex\fR
.P
Remove a development dependency:
    $ \fBcargo rm regex \-\-dev\fR
.P
Remove a build dependency:
    $ \fBcargo rm regex \-\-build\fR
.SH SEE ALSO
\fBcargo\fR(1), \fBcargo-add\fR(1), \fBcargo-upgrade\fR(1)
