.TH CSV2SVG "1" "April 2024" "csv2svg 0.2.1" "User Commands"
.SH NAME
csv2svg \- take a csv as input and output svg
.SH SYNOPSIS
.B csv2svg
[\fI\,-v\/\fR] [\fI\,-f <format>\/\fR]
.SH DESCRIPTION
Build an SVG graph from a csv document.
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-version\fR
print the version
.TP
\fB\-f\fR, \fB\-\-format\fR
output format: "svg" or "html"
.TP
\fB\-\-help\fR
display usage information
.SH "SEE ALSO"
The full documentation for
.B csv2svg
is maintained as a Texinfo manual.  If the
.B info
and
.B csv2svg
programs are properly installed at your site, the command
.IP
.B info csv2svg
.PP
should give you access to the complete manual.
