.TH ASAHI-BLESS "1" "April 2025" "asahi-bless" "User Commands"
.SH NAME
asahi-bless \- list boot volumes and select the active one on Apple
Silicon Macs
.SH SYNOPSIS
.B asahi-bless
[\fI\,OPTIONS\/\fR]
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR <DEVICE>
Path to the nvram device
.TP
\fB\-n\fR, \fB\-\-next\fR
Set boot volume for next boot only
.TP
\fB\-l\fR, \fB\-\-list\-volumes\fR
List boot volume candidates
.TP
\fB\-\-set\-boot\fR <NAME_OR_INDEX>
Set boot volume by name or index, as displayed with \fB--list-volumes\fR.
Without this option the program runs in interactive mode
.TP
\fB\-\-set\-boot\-macos\fR
Set boot volume to macOS if unambiguous
.TP
\fB\-y\fR, \fB\-\-yes\fR
Do not ask for confirmation
.TP
\fB\-\-get\-boot\fR
Get currently selected boot target. May be combined with
\fB\-\-next\fR to show the next boot target
.TP
\fB\-\-clear\-next\fR
Clear the selected next boot target
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
