.TH SWTCHRD "1" "June 2024" "swtchrd 0.1.2" "User Commands"
.SH NAME
swtchrd \- manual page for swtchrd 0.1.2
.SH SYNOPSIS
.B swtchrd
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
A Gnome\-style window switcher for the Sway window manager.
.PP
This is the command to start the swtchr daemon. You should run this command when you start your Sway session, either via your Sway config or via a systemd service.
.SH OPTIONS
.HP
\fB\-c\fR, \fB\-\-config\fR <PATH>
.IP
Override the path of the config file
.HP
\fB\-\-no\-check\fR
.IP
Skip checking that the daemon is running in a Sway session
.HP
\fB\-h\fR, \fB\-\-help\fR
.IP
Print help (see a summary with '\-h')
.HP
\fB\-V\fR, \fB\-\-version\fR
.IP
Print version
.SH "SEE ALSO"
The full documentation for
.B swtchrd
is maintained as a Texinfo manual.  If the
.B info
and
.B swtchrd
programs are properly installed at your site, the command
.IP
.B info swtchrd
.PP
should give you access to the complete manual.

