.TH SWTCHR "1" "June 2024" "swtchr 0.1.2" "User Commands"
.SH NAME
swtchr \- manual page for swtchr 0.1.2
.SH SYNOPSIS
.B swtchr
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
A Gnome\-style window switcher for the Sway window manager.
.PP
This is the client command for signaling to the swtchr daemon to open the window switcher overlay.
.PP
To use swtchr, bind this command to a keyboard shortcut in your Sway config.
.SH OPTIONS
.HP
\fB\-\-no\-check\fR
.IP
Skip checking that the client is running in a Sway session
.HP
\fB\-h\fR, \fB\-\-help\fR
.IP
Print help (see a summary with '\-h')
.HP
\fB\-V\fR, \fB\-\-version\fR
.IP
Print version
