.TH RIPASSO-CURSIVE 1
.SH NAME
ripasso\-cursive \- A password manager that uses the file format of the standard unix password manager 'pass', implemented in rust.
.SH SYNOPSIS
\fBripasso\-cursive\fR [FLAGS]
.SH DESCRIPTION
ripasso\-cursive is an curses application that lets you manage your or your teams passwords.The passwords are encrypted with pgp and optionally stored in an git repository. The list of team members are stored in the file .gpg\-id, one pgp key id per line.
.SH FLAGS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a help text
.SH KEYBOARD SHORTCUTS
Enter : Copy the current selected password to the copy buffer for 40 seconds

Delete : Delete the marked password

Insert : Create a new password entry

Control + y : same as Enter

Control + b : if the password have an otpauth:// url in it, generate a code and store it in the copy buffer

Control + n : move marker down

Control + p : move marker up

Control + r : rename the password without changing it's content

Control + u : copy the filename of the password

Control + h : show the git history of the password

Control + v : view the list of team members

Control + o : open a password edit dialog

Control + f : pull from the git repository

Control + g : push to the git repository

Escape : quit 


.SH USAGE NOTE
ripasso\-cursive reads $HOME/.password\-store/ by default, override this by setting
the PASSWORD_STORE_DIR environmental variable.

If you specify the PASSWORD_STORE_SIGNING_KEY environmental variable, then
ripasso will verify that the .gpg\-id file is correctly signed. Valid values are one or more 40 character pgp fingerprints,
separated by commas.


.SH CONFIG FILE
ripasso reads configuration from $XDG_CONFIG_HOME/ripasso/settings.toml

Example config file

[stores]

  [stores.default]

    path = "/home/user/.password\-store/"

    valid_signing_keys = "AF77DAC5B3882EAD316B7312D5B659E1D2FDF0C3"

  [stores.work]

    path = "/home/user/.work_pass/"

    style_path = "/home/user/.config/ripasso/work\-style.toml"



Valid settings for a store are:

path : This is the root path to the password store directory

valid_signing_keys : this setting corresponds to the PASSWORD_STORE_SIGNING_KEY environmental variable

style_path : color and style information for the store, different stores can have different styles and they will
change when you switch store. Documentation on the format can be found here https://docs.rs/cursive_core/0.1.1/cursive_core/theme/index.html

pgp : the pgp implementation to use for the store, valid values are gpg or sequoia

own_fingerprint : if the pgp option is set to sequoia, ripasso needs to know the fingerprint of your own key in order to communicate with gpg\-agent


.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.
.SH AUTHORS
.P
.RS 2
.nf
Joakim Lundborg <joakim.lundborg@gmail.com>
Alexander Kjäll <alexander.kjall@gmail.com>
