.TH ASAHI-BTSYNC "1" "April 2025" "asahi-btsync" "User Commands"
.SH NAME
asahi-btsync \- list bluetooth pairing keys set up by macOS on Apple
Silicon Macs and sync them to a local configuration for bluez
.SH SYNOPSIS
asahi\-btsync [OPTIONS] [SUBCOMMAND]
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR <DEVICE>
Path to the nvram device
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
dump
Dump binary bluetooth device info from nvram
.TP
help
Print top-level help or the help of the given subcommand(s)
.TP
list
Parse shared bluetooth keys from nvram
.TP
sync
Sync bluetooth device information from nvram to a bluez configuration
(default path: /var/lib/bluetooth). Accepts option \fB-c\fR,
\fB--config\fR <PATH> for non-default configuration paths
