.TH ASAHI-NVRAM "1" "April 2025" "asahi-nvram" "User Commands"
.SH NAME
asahi-nvram \- read and write nvram variables on Apple Silicon Macs
.SH SYNOPSIS
asahi\-nvram [OPTIONS] [SUBCOMMAND]
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR <DEVICE>
Path to the nvram device
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
delete
Delete nvram variables. Accepts multiple nvram variables as arguments
.TP
help
Print top-level help or the help of the given subcommand(s)
.TP
read
Read nvram variables. Accepts multiple nvram variables as arguments
.TP
write
Write nvram variables. Accepts multiple nvram variable assignments
in the form <VAR>=<VALUE> as arguments
.SH NVRAM VARIABLE FORMAT
Nvram variables are parsed in the format <PARTITION>:<NAME>, where
<PARTITION> is one of 'system' or 'common'.
.SH WARNING
Writing to nvram may result in having to perform a DFU restore. Avoid
unless you know what you're doing.
