.TH TRAWLDB 1 "2022" "trawldb version" "User Commands"
.SH NAME
trawldb \- CLI for managing trawl configuration resources
.SH SYNOPSIS
.B trawldb
[OPTIONS] [--] [FILENAME]
.SH DESCRIPTION
.B trawldb
is a client CLI utility that allows for managing configuration resources stored by Trawl. Trawl is a resource management tool aimed as an xrdb alternative that is session independent, i.e works on both X11 and Wayland.
.SH OPTIONS
.TP
.B -b, --backup <string>
backup suffix for -edit (default .bak )
.TP
.B -c, --cpp <CPP>
preprocessor to use (default /usr/bin/cpp )
.TP
.B -D, --define <DEFINE>
.TP
.B -e, --edit <filename>
edit resources into file
.TP
.B -g, --get <name>
get the content of a resource
.TP
.B -h, --help
Print help information
.TP
.B -I, --include <INCLUDE>
.TP
.B -l, --load <filename>
load resources from file
.TP
.B -m, --merge <filename>
merge resources from file & sort
.TP
.B --nocpp
do not use a preprocessor
.TP
.B -q, --query [<string>...]
query resources
.TP
.B --remove
remove resources
.TP
.B -V, --version
Print version information
.SH AUTHORS
Soumya Ranjan Patnaik <soumyaranjan1812@gmail.com>, Ken Gilmer <kgilmer@gmail.com>
