.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq autocrypt decode \- Read Autocrypt\-encoded certificates
.SH SYNOPSIS
.br
\fBsq autocrypt decode\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Read Autocrypt\-encoded certificates.
.PP
Given an autocrypt header (or an key\-gossip header), this command
extracts the certificate encoded within it.
.PP
The converse operation is `sq autocrypt encode\-sender`.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emit binary data
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write to FILE or stdout if omitted
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Extract all certificates from a mail
.PP
.nf
.RS
sq autocrypt decode autocrypt.eml
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-autocrypt\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
