.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq autocrypt import \- Import Autocrypt\-encoded certificates
.SH SYNOPSIS
.br
\fBsq autocrypt import\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Import Autocrypt\-encoded certificates.
.PP
Given a mail containing autocrypt headers (or an key\-gossip headers),
this command extracts and imports the certificates encoded within it.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-\-recipient\-file\fR=\fIKEY_FILE\fR
Decrypt the message using the key in KEY_FILE
.TP
\fB\-\-session\-key\fR=\fISESSION\-KEY\fR
Decrypt an encrypted message using SESSION\-KEY
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Imports all certificates from a mail
.PP
.nf
.RS
sq autocrypt import autocrypt.eml
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-autocrypt\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
