.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq cert import \- Import certificates into the local certificate store
.SH SYNOPSIS
.br
\fBsq cert import\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Import certificates into the local certificate store.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Import a certificate.
.PP
.nf
.RS
sq cert import juliet.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-cert\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
