.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq key adopt \- Bind keys from one certificate to another
.SH SYNOPSIS
.br
\fBsq key adopt\fR [\fIOPTIONS\fR] \fITARGET\-KEY\fR
.SH DESCRIPTION
Bind keys from one certificate to another.
.PP
This command allows one to transfer primary keys and subkeys into an
existing certificate.  Say you want to transition to a new
certificate, but have an authentication subkey on your current
certificate.  You want to keep the authentication subkey because it
allows access to SSH servers and updating their configuration is not
feasible.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emit binary data
.TP
\fB\-\-allow\-broken\-crypto\fR
Allow adopting keys from certificates using broken cryptography
.TP
\fB\-\-expire\fR=\fIKEY\-EXPIRATION\-TIME\fR
Make adopted subkeys expire at the given time
.TP
\fB\-k\fR, \fB\-\-key\fR=\fIKEY\fR
Add the key or subkey KEY to the TARGET\-KEY
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write to FILE or stdout if omitted
.TP
 \fITARGET\-KEY\fR
Add keys to TARGET\-KEY or reads keys from stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Adopt an subkey into the new cert
.PP
.nf
.RS
sq key adopt \-\-keyring juliet\-old.pgp \-\-key 0123456789ABCDEF \\
.RE
.RS
.RS
juliet\-new.pgp
.RE
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-key\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
