.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq key attest\-certifications \- Attest to third\-party certifications
.SH SYNOPSIS
.br
\fBsq key attest\-certifications\fR [\fIOPTIONS\fR] \fIKEY\fR
.SH DESCRIPTION
Attest to third\-party certifications allowing for their distribution.
.PP
To prevent certificate flooding attacks, modern key servers prevent
uncontrolled distribution of third\-party certifications on
certificates.  To make the key holder the sovereign over the
information over what information is distributed with the certificate,
the key holder needs to explicitly attest to third\-party
certifications.
.PP
After the attestation has been created, the certificate has to be
distributed, e.g. by uploading it to a key server.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emit binary data
.TP
\fB\-\-all\fR
Attest to all certifications [default]
.TP
\fB\-\-none\fR
Remove all prior attestations
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write to FILE or stdout if omitted
.TP
 \fIKEY\fR
Change attestations on KEY or reads from stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Attest to all certifications present on the key
.PP
.nf
.RS
sq key attest\-certifications juliet.pgp
.RE
.PP
.fi

.PP
Retract prior attestations on the key
.PP
.nf
.RS
sq key attest\-certifications \-\-none juliet.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-key\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
