.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq network keyserver publish \- Publish certificates on key servers
.SH SYNOPSIS
.br
\fBsq network keyserver publish\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Publish certificates on key servers.
.PP
Sends certificates to the configured key servers for publication.  By
default, the certificates are sent to `hkps://keys.openpgp.org`, `hkps://mail\-api.proton.me`, `hkps://keys.mailvelope.com`, `hkps://keyserver.ubuntu.com`, and `hkps://sks.pod01.fleetstreetops.com`.  This can be tweaked using
`\-\-servers`.

.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-\-require\-all\fR
Require that all publish operations succeed and return an error otherwise.  By default we only require that one publish operation succeeds.
.TP
\fB\-s\fR, \fB\-\-server\fR=\fIURI\fR
Set the key server to use.  Can be given multiple times.
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-network\fR(1), \fBsq\-network\-keyserver\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
