.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq network wkd fetch \- Retrieve certificates from a Web Key Directory
.SH SYNOPSIS
.br
\fBsq network wkd fetch\fR [\fIOPTIONS\fR] \fIADDRESS\fR
.SH DESCRIPTION
Retrieve certificates from a Web Key Directory.
.PP
By default, any returned certificates are stored in the local
certificate store.  This can be overridden by using `\-\-output`
option.
.PP
When a certificate is retrieved from a WKD, and imported into the
local certificate store, any User IDs with the email address that was
looked up are certificated with a local WKD\-specific key.  That proxy
certificate is in turn certified as a minimally trusted CA (trust
amount: 1 of 120) by the local trust root.  How much the WKD proxy CA
is trusted can be tuned using `sq pki link add` or `sq pki link retract`
in the usual way.
.PP

.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emit binary data
.TP
\fB\-\-all\fR
Fetch updates for all known certificates
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write to FILE (or stdout when omitted) instead of importing into the certificate store
.TP
 \fIADDRESS\fR
Retrieve certificate(s) for ADDRESS
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-network\fR(1), \fBsq\-network\-wkd\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
