.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq network wkd url \- Print the advanced Web Key Directory URL of an email address
.SH SYNOPSIS
.br
\fBsq network wkd url\fR [\fIOPTIONS\fR] \fIADDRESS\fR
.SH DESCRIPTION
Print the advanced Web Key Directory URL of an email address.
.SH OPTIONS
.SS "Subcommand options"
.TP
 \fIADDRESS\fR
Query for ADDRESS
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-network\fR(1), \fBsq\-network\-wkd\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
