.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq pki link list \- List links
.SH SYNOPSIS
.br
\fBsq pki link list\fR [\fIOPTIONS\fR]  
.SH DESCRIPTION
List links.
.PP
This command lists all bindings that are linked or whose link has been
retracted.
.PP

.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-\-ca\fR
Only lists bindings linked as CAs.  That is, only list a link if its trust depth is greater than 0.
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-pki\fR(1), \fBsq\-pki\-link\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
