.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq toolbox keyring list \- List keys in a keyring
.SH SYNOPSIS
.br
\fBsq toolbox keyring list\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
List keys in a keyring.
.PP
Prints the fingerprint as well as the primary userid for every
certificate encountered in the keyring.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-\-all\-userids\fR
List all user ids, even those that are expired, revoked, or not valid under the standard policy.
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
List all certs
.PP
.nf
.RS
sq toolbox keyring list certs.pgp
.RE
.PP
.fi

.PP
List all certs with a userid on example.org
.PP
.nf
.RS
sq toolbox keyring filter \-\-domain example.org certs.pgp \\
.RE
.RS
.RS
| sq toolbox keyring list
.RE
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-toolbox\fR(1), \fBsq\-toolbox\-keyring\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
