.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq toolbox keyring split \- Split a keyring into individual keys
.SH SYNOPSIS
.br
\fBsq toolbox keyring split\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Split a keyring into individual keys.
.PP
Splitting up a keyring into individual keys helps with curating a
keyring.
.PP
The converse operation is `sq toolbox keyring merge`.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emit binary data
.TP
\fB\-p\fR, \fB\-\-prefix\fR=\fIPREFIX\fR
Write to files with PREFIX [defaults: `FILE\-` if FILE is set, or `output\-` if read from stdin]
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Split all certs
.PP
.nf
.RS
sq toolbox keyring split certs.pgp
.RE
.PP
.fi

.PP
Split all certs, merging them first to avoid duplicates
.PP
.nf
.RS
sq toolbox keyring merge certs.pgp | sq toolbox keyring split
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-toolbox\fR(1), \fBsq\-toolbox\-keyring\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
