.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq toolbox armor \- Convert binary to ASCII
.SH SYNOPSIS
.br
\fBsq toolbox armor\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Convert binary to ASCII.
.PP
To make encrypted data easier to handle and transport, OpenPGP data
can be transformed to an ASCII representation called ASCII Armor.  sq
emits armored data by default, but this subcommand can be used to
convert existing OpenPGP data to its ASCII\-encoded representation.
.PP
The converse operation is `sq toolbox dearmor`.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-\-label\fR=\fILABEL\fR
Select the kind of armor header
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write to FILE or stdout if omitted
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Convert a binary certificate to ASCII
.PP
.nf
.RS
sq toolbox armor binary\-juliet.pgp
.RE
.PP
.fi

.PP
Convert a binary message to ASCII
.PP
.nf
.RS
sq toolbox armor binary\-message.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-toolbox\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
