.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq toolbox packet decrypt \- Unwrap an encryption container
.SH SYNOPSIS
.br
\fBsq toolbox packet decrypt\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Unwrap an encryption container.
.PP
Decrypts a message, dumping the content of the encryption container
without further processing.  The result is a valid OpenPGP message
that can, among other things, be inspected using `sq toolbox packet dump`.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emit binary data
.TP
\fB\-\-dump\-session\-key\fR
Print the session key to stderr
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write to FILE or stdout if omitted
.TP
\fB\-\-private\-key\-store\fR=\fIKEY_STORE\fR
Provide parameters for private key store
.TP
\fB\-\-recipient\-file\fR=\fIKEY_FILE\fR
Decrypt the message using the key in KEY_FILE
.TP
\fB\-\-session\-key\fR=\fISESSION\-KEY\fR
Decrypt an encrypted message using SESSION\-KEY
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Unwraps the encryption revealing the signed message
.PP
.nf
.RS
sq toolbox packet decrypt \-\-recipient\-file juliet.pgp \\
.RE
.RS
.RS
ciphertext.pgp
.RE
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-toolbox\fR(1), \fBsq\-toolbox\-packet\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
