.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq toolbox packet join \- Join packets split across files
.SH SYNOPSIS
.br
\fBsq toolbox packet join\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Join packets split across files.
.PP
Splitting a packet sequence into individual packets, then recombining
them freely with `sq toolbox packet join` is a great way to experiment with
OpenPGP data.
.PP
The converse operation is `sq toolbox packet split`.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emit binary data
.TP
\fB\-\-label\fR=\fILABEL\fR
Select the kind of armor header
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write to FILE or stdout if omitted
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Split a certificate into individual packets
.PP
.nf
.RS
sq toolbox packet split juliet.pgp
.RE
.PP
.fi

.PP
Then join only a subset of these packets
.PP
.nf
.RS
sq toolbox packet join juliet.pgp\-[0\-3]*
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-toolbox\fR(1), \fBsq\-toolbox\-packet\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
