.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq toolbox packet split \- Split a message into packets
.SH SYNOPSIS
.br
\fBsq toolbox packet split\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Split a message into packets.
.PP
Splitting a packet sequence into individual packets, then recombining
them freely with `sq toolbox packet join` is a great way to experiment with
OpenPGP data.
.PP
The converse operation is `sq toolbox packet join`.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-B\fR, \fB\-\-binary\fR
Emit binary data
.TP
\fB\-p\fR, \fB\-\-prefix\fR=\fIPREFIX\fR
Write to files with PREFIX [defaults: `FILE\-` if FILE is set, or `output\-` if read from stdin]
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Split a certificate into individual packets
.PP
.nf
.RS
sq toolbox packet split juliet.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-toolbox\fR(1), \fBsq\-toolbox\-packet\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
