.TH SQ 1 0.34.0 "Sequoia PGP" "User Commands"
.SH NAME
sq toolbox dearmor \- Convert ASCII to binary
.SH SYNOPSIS
.br
\fBsq toolbox dearmor\fR [\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
Convert ASCII to binary.
.PP
To make encrypted data easier to handle and transport, OpenPGP data
can be transformed to an ASCII representation called ASCII Armor.  sq
transparently handles armored data, but this subcommand can be used to
explicitly convert existing ASCII\-encoded OpenPGP data to its binary
representation.
.PP
The converse operation is `sq toolbox armor`.
.PP


.SH OPTIONS
.SS "Subcommand options"
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write to FILE or stdout if omitted
.TP
 \fIFILE\fR
Read from FILE or stdin if omitted
.SS "Global options"
See \fBsq\fR(1) for a description of the global options.
.SH EXAMPLES
.PP

.PP
Convert a ASCII certificate to binary
.PP
.nf
.RS
sq toolbox dearmor ascii\-juliet.pgp
.RE
.PP
.fi

.PP
Convert a ASCII message to binary
.PP
.nf
.RS
sq toolbox dearmor ascii\-message.pgp
.RE
.fi
.SH "SEE ALSO"
.nh
\fBsq\fR(1), \fBsq\-toolbox\fR(1).
.hy
.PP
For the full documentation see <https://book.sequoia\-pgp.org>.
.SH VERSION
0.34.0 (sequoia\-openpgp 1.19.0)
