.TH REGOLITH-POWERD 1 "Regolith Power Daemon Man Page"
.SH NAME
regolith-powerd \- Power Settings Daemon for Regolith Wayland Session
.SH SYNOPSIS
.B regolith-powerd
.SH DESCRIPTION
regolith-powerd uses systemd-inhibit to block power button and lid switch events via logind; letting those be handled by sway instead. It also allows for launching and configuraing swayidle using gnome-control-center or gsettings

.SH SEE ALSO
.BR swayidle(1)
.BR systemd-inhibit(1)
.SH AUTHOR
Soumya Ranjan Patniak <soumyaranjan1812@gmail.com>

