.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2024 Maytham Alsudany <maytha8thedev@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BLIGHT 1 "2024-05-01"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
blight \- Hassle-free CLI backlight utility for Linux
.SH SYNOPSIS
.B blight
.RI [ options ] " command " [ value ]
.SH DESCRIPTION
This manual page documents the
.B blight
program.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBblight\fP is a hassle-free CLI utility to manage backlight on Linux; one that plays well
with hybrid GPU configuration and proprietary drivers.
.SH FLAGS
.TP
.B \-s, \-\-sweep
Lets you increase brightness gradually, resulting in a smooth change.
Can only be used with the inc and dec commands.
.TP
.B \-d, \-\-device <name>
Lets you specify a backlight device target other than the default one.
Can only be used with the inc, dec, set, save and status commands.
.SH COMMANDS
.TP
\fBinc\fP <value> [-s | --sweep] [-d | --device <name>]
Increase brightness by the given value.
.TP
\fBdec\fP <value> [-s | --sweep] [-d | --device <name>]
Decrease brightness by the given value.
.TP
\fBset\fP <value> [-d | --device <name>]
Set brightness to the given value.
.TP
\fBsave\fP [-d | --device <name>]
Save current brightness value to restore later.
.TP
\fBrestore\fP
Restore saved brightness value.
.TP
\fBsetup\fP
Install udev rules and add user to video group (run with sudo).
.TP
\fBstatus\fP [-d | --device <name>]
Show backlight device status.
.TP
\fBlist\fP
List all backlight devices.
.TP
\fBhelp\fP
Display help.
.SH SEE ALSO
.br
The program is documented fully at
.IR /usr/share/doc/blight/README.md .
