.TH SQ-KEYRING-LINTER "1" "October 2020" "sequoia-keyring-linter 0.1.0" "User Commands"
.SH NAME
sqv \- OpenPGP keyring linter
.SH DESCRIPTION
sq-keyring-linter 0.1.0
sq-keyring-linter is a command\-line tool to identify problems with OpenPGP certificates.
.SH USAGE
.IP
sq-keyring-linter <KEYRING>
.SH OPTIONS
.TP
No flags or options at this time.
.SH ARGS
.TP
<KEYRING>
A filename that contains a "PGP keyring".  That is, a concatenated
series of OpenPGP certificates, typically in binary form.
.SH OUTPUT
The tool emits a textual description of concerns that it found.
Please do not parse the output, as it is subject to change.
