.TH ASAHI-WIFISYNC "1" "April 2025" "asahi-wifisync" "User Commands"
.SH NAME
asahi-wifisync \- list the WiFi information set up by macOS on Apple
Silicon Macs and sync WiFi passwords to a local configuration for iwd
.SH SYNOPSIS
asahi\-wifisync [OPTIONS] [SUBCOMMAND]
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR <DEVICE>
Path to the nvram device
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
help
Print top-level help or the help of the given subcommand(s)
.TP
list
Parse shared wlan keys from nvram
.TP
sync
Sync wlan information from nvram to an iwd configuration (default path:
/var/lib/iwd). Accepts option \fB-c\fR, \fB--config\fR <PATH> for
non-default configuration paths
