.TH SHA1CDSUM "1" "December 2020" "sha1collisiondetection" "User Commands"
.SH NAME
sha1cdsum \- SHA\-1 Collision Detection
.SH DESCRIPTION
sha1cdsum does a SHA\-1 cryptographic digest, but diverges from SHA\-1
when it encounters the most common forms of attack against the
algorithm's collision resistance.
.PP
When such an attack is detected, it produces a different digest and
indicates that a collision block was observed.
.SS USAGE
.B sha1cdsum
reads and calculates over data it receives on standard input, and
ignores all command line options.  But see the WARNING below about
interface stability.
.SS EXAMPLE
.nf
\f[C]
$ sha1cdsum < /dev/null
this is a stub implementation!
da39a3ee5e6b4b0d3255bfef95601890afd80709
$ zcat /usr/share/doc/sha1cdsum/examples/shattered-1.pdf.gz | sha1cdsum
this is a stub implementation!
*coll* e1761773e6a35916d99f891b77663e6405313587
$ 
\f[R]
.fi
.SS WARNING
The API for this command is unstable and likely to change!  See
https://gitlab.com/sequoia-pgp/sha1collisiondetection/-/issues/2 for details.
.SS SEE ALSO
.BR https://shattered.io/
.PP
.BR https://sha\-mbles.github.io/
.PP
.BR https://gitlab.com/sequoia-pgp/sha1collisiondetection
